apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: eu-west-1
  # version: "1.20"


# check these
# managedNodeGroups:
#   - name: acme-test-cluster
#     minSize: 3
#     maxSize: 7
#     desiredCapacity: 3
#     instanceType: m5.2xlarge

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: false
    ssh:
      allow: true
      publicKeyName: devops-account-ireland
