apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-docker-app
  namespace: go-app
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: 89**********.dkr.ecr.eu-west-1.amazonaws.com/go-backend-app:latest
          name: backend
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: go-docker-app
  namespace: go-app
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    io.kompose.service: backend
  type: LoadBalancer
status:
  loadBalancer: {}
